# Generated by Django 3.0.4 on 2020-04-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('img', models.URLField(max_length=500)),
                ('link', models.URLField(max_length=600)),
            ],
        ),
    ]
